baseURL = "https://slang-dictionary.netlify.app/"
languageCode = "en-us"
title = "Slang Dictionary"
theme = "brionz-base"
sectionPagesMenu = "main"
googleAnalytics = "UA-123-452-1"
summaryLength = "25"

[params]
  title = "Slang Dictionary"
  description = "Самый актуальный словарь современного сленга."
  mainSections = ["posts"]  # Это заставит тему искать посты для главной
