backend:
  name: git-gateway
  branch: master # Убедитесь, что это имя вашей главной ветки (main или master)

media_folder: "static/img" # Папка для загрузки изображений
public_folder: "/img"      # Путь для доступа к изображениям

collections:
  - name: "posts"
    label: "Словарные статьи"
    folder: "content/posts" # Папка, куда Hugo сохраняет статьи
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок (Сленговое слово)", name: "title", widget: "string"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Теги", name: "tags", widget: "list", required: false}
      - {label: "Тело статьи (Определение)", name: "body", widget: "markdown"}
